# Generated by Django 6.0.6 on 2026-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
    ]
