# Generated by Django 6.0.6 on 2026-07-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsystem', '0004_order_address_order_phone_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ទីតាំង/អាសយដ្ឋានហាង'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ម៉ោងបិទលក់'),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ម៉ោងបើកលក់'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='លេខទូរស័ព្ទហាង'),
        ),
    ]
