# Generated by Django 6.0.6 on 2026-07-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsystem', '0005_shop_address_shop_closing_time_shop_opening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នាផលិតផល'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='ការបញ្ចុះតម្លៃ (%)'),
        ),
    ]
